<?php

/**
 * @file
 * Test module for State Machine.
 */

use Drupal\views\EntityViewsData;

/**
 * Implements hook_entity_type_build().
 */
function state_machine_test_entity_type_build(array &$entity_types) {
  $entity_types['entity_test_with_bundle']->setHandlerClass('views_data', EntityViewsData::class);
}

/**
 * Workflow callback for the "Second" bundle of entity_test_with_bundle.
 */
function state_machine_test_workflow_callback() {
  return 'validation';
}
